### ISSUE TITLE
Can you explain the parameter adjtype in detail?

### ISSUE THREAD

**Issue by michealowen** [guokan987/HGCN#2]
If i want to use the gated-stgcn model, should i edit the parameters?

**Comment by michealowen** [comment]
If i want to use the gated-stgcn model, should i edit the parameters?

**Comment by guokan987** [comment]
you should revised "--model Gated_STGCN", --model: the model you can select in train.py

**Comment by michealowen** [comment]
> you should revised "--model Gated_STGCN", --model: the model you can select in train.py

But I 

> you should revised "--model Gated_STGCN", --model: the model you can select in train.py

There are several kinds of 'adjtype', but i can not find the explaination about this parameter.

**Comment by michealowen** [comment]
> you should revised "--model Gated_STGCN", --model: the model you can select in train.py

There are several kinds of 'adjtype', but i can not find the explaination about this parameter.

**Comment by guokan987** [comment]
> > you should revised "--model Gated_STGCN", --model: the model you can select in train.py
> 
> There are several kinds of 'adjtype', but i can not find the explaination about this parameter.

Please see the details of util.py, and we define the type of adjacent matrix by 'adjtype'
