### ISSUE TITLE
The results are very different

### ISSUE THREAD

**Issue by Wanghongyu97** [guokan987/HGCN#3]
The results of code running on the computer and running on the server are very different

**Comment by guokan987** [comment]
> The results of code running on the computer and running on the server are very different

这个，我也说不清楚了，我在服务器2080ti上跑的，。。。，别的人也是在服务器上重现的。。。

**Comment by Wanghongyu97** [comment]
> > The results of code running on the computer and running on the server are very different
> 
> 这个，我也说不清楚了，我在服务器2080ti上跑的，。。。，别的人也是在服务器上重现的。。。

谢谢，在服务器上我也重现了。就是我很惊讶，在电脑上跑的结果比服务器上要高很多，所以我就来问问你，那没啥事了，谢谢！
